- name: Teste conexao
  hosts: all
  become: true  # Para usar sudo
  tasks:
    - name: Testando conexao
      ansible.builtin.ping:


- name: Instalação e configuração samba
  hosts: all
  become: true
  tasks:
    - name: Samba install
      ansible.builtin.package:
        name:
          - samba
        state: present

- name: Criando diretorio para samba
  hosts: all
  become: true
  tasks:
    - name: Criando diretorio /opt/arquivos
      ansible.builtin.file:
        path: /opt/arquivos
        state: directory
        owner: root
        group: root
        mode: '755'
